int tmin();
int test_tmin();
int isEqual(int, int);
int test_isEqual(int, int);
int evenBits();
int test_evenBits();
int getByte(int, int);
int test_getByte(int, int);
int anyOddBit();
int test_anyOddBit();
int isNegative(int);
int test_isNegative(int);
int isPositive(int);
int test_isPositive(int);
int sign(int);
int test_sign(int);
int replaceByte(int, int, int);
int test_replaceByte(int, int, int);
unsigned float_twice(unsigned);
unsigned test_float_twice(unsigned);
